{"name": "test_div[divisorfail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_calc.TestCalc object at 0x0000023BC1368670>, a = 7, b = 0, expect = 0, get_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>, caculate = None\n\n    @pytest.mark.parametrize(\"a,b,expect\", divdatas_data, ids=myid_div)\n    @pytest.mark.run(order=4)\n    def test_div(self, a, b, expect,get_calc,caculate):\n        # 判断b不能等于0\n        if b == 0:\n            print(\"除数不能等于0\")\n>           assert False\nE           assert False\n\ntest_calc.py:81: AssertionError"}, "attachments": [{"name": "stdout", "source": "b9e9ba8e-c377-4ae2-a244-1e91d957aeab-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "7"}, {"name": "b", "value": "0"}, {"name": "expect", "value": "0"}], "start": 1612147341890, "stop": 1612147341890, "uuid": "44ced93d-2d74-47b5-ba05-07dffa2508df", "historyId": "e31e120dabf62fe3b57c39d9f71be492", "testCaseId": "4a57f615ae930c12d705a9fc7a66b88d", "fullName": "test_calc.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-CV4D84I5"}, {"name": "thread", "value": "32636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}