{"name": "test_sub[0--999999999999999-999999999999999]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_calc.TestCalc object at 0x0000023BC1279E20>, a = 0, b = -999999999999999, expect = 999999999999999\nget_calc = <test_code.calc.Calculator object at 0x0000023BC1308670>\n\n    @pytest.mark.parametrize(\"a,b,expect\", subdatas_data)\n    @pytest.mark.run(order=2)\n    def test_sub(self, a, b, expect,get_calc):\n    \n        if isinstance(a, str):\n            print(\"非数字类型\")\n            assert False\n    \n        elif a is None:\n            print(\"不能为空\")\n            assert False\n    \n        elif 999999 <= b or b <= -999999:\n            print(\"超出最大值\")\n>           assert False\nE           assert False\n\ntest_calc.py:113: AssertionError"}, "attachments": [{"name": "stdout", "source": "9bf3c0ee-86f9-4234-bcbb-551696258403-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "0"}, {"name": "b", "value": "-999999999999999"}, {"name": "expect", "value": "999999999999999"}], "start": 1612147341768, "stop": 1612147341769, "uuid": "b8723660-f1df-4059-ad08-b889750b024a", "historyId": "3b2d2c6b28c66259e592b0a32051cfec", "testCaseId": "3b960671b7ce69bb509e37e84b3024bc", "fullName": "test_calc.TestCalc#test_sub", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-CV4D84I5"}, {"name": "thread", "value": "32636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}